main: gg.playtogether.mc.App
name: MaSHelper
version: 0.1
description: A helper plugin for the Mine and Seek project with various utilities.
api-version: '1.20'
author: LordKanelsnegle
website: https://github.com/LordKanelsnegle/MaSPlugin
commands:
  pull:
    description: Runs a script to pull updates to the MaS datapack.
    usage: /<command>
    permission: mashelper.admin
    permission-message: You don't have permission.
  save:
    description: Save the structures in the build area.
    usage: /<command> <map-name>
    permission: mashelper.builder
    permission-message: You don't have permission.
